// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Account struct {
	ID        int32
	UserID    sql.NullInt32
	Balance   sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type TransactionHistory struct {
	ID              int32
	TransactionType sql.NullString
	Amount          sql.NullInt64
	UserID          sql.NullInt32
	AccountID       sql.NullInt32
	Timestamp       sql.NullTime
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type User struct {
	ID        int32
	Name      sql.NullString
	Email     sql.NullString
	Password  sql.NullString
	Status    sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
